server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      global:
        corsConfigurations:
          '[/api/v1/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
              - HEAD
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -   id: auth-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/auth/register, /api/v1/auth/login, /api/v1/auth/validate-token, /api/v1/auth/refresh-token

        -   id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/order/**
            filters:
              - name: JwtAuthFilter

        -   id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/product/**
            filters:
              - name: JwtAuthFilter

        -   id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/user/**
            filters:
              - name: JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}


resilience4j:
  circuitbreaker:
    instances:
      authCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException

  timelimiter:
    configs:
      default:
        timeout-duration: 3s

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 5s

jwt:
  header: Authorization
  secret: ANMGN10M0EI76QJPOOCAKRD1RJ98C6AACBIM8YYCJKMH43VTD52IRJE8N0DEOB70
  expiration: 6048000