server:
  port: 8060
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/product
    username: furkan
    password: furkan
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${EUREKA_HOST:localhost}